apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  chart:
    spec:
      chart: loki
      version: 5.39.0
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: loki
  values:
    loki: 
      auth_enabled: false
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: loki-distributed-basic-auth
        nginx.ingress.kubernetes.io/auth-secret-type: auth-map
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Scope-OrgID $remote_user;
      labels:
         blackbox.monitoring.exclude: "true"
      paths:
        write:
          - /api/prom/push
          - /loki/api/v1/push
        read:
          - /api/prom/tail
          - /loki/api/v1/tail
          - /loki/api
          - /api/prom/rules
          - /loki/api/v1/rules
          - /prometheus/api/v1/rules
          - /prometheus/api/v1/alerts
        singleBinary:
          - /api/prom/push
          - /loki/api/v1/push
          - /api/prom/tail
          - /loki/api/v1/tail
          - /loki/api
          - /api/prom/rules
          - /loki/api/v1/rules
          - /prometheus/api/v1/rules
          - /prometheus/api/v1/alerts
      hosts:
        - loki.domain.com
    backend:
      replicas: 1
    read:
      replicas: 1
    write:
      replicas: 1
    test:
      enabled: false