apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  chart:
    spec:
      chart: loki
      version: 5.39.0
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: loki
  values:
    loki: 
      auth_enabled: false
    ingress:
      enabled: true
      hosts:
        - host: loki.domain.com
          paths:
            - path: /
    backend:
      replicas: 1
    read:
      replicas: 1
    write:
      replicas: 1
    test:
      enabled: false